language: python
python: '2.7'
sudo: required

branches:
    only:
        - /^feature.*$/
        - /^redcap.*$/
        - develop
        - master
env:
    - CI_REDCAP_ZIP=redcap6.5.3.zip SHARED_FOLDER=./vagrant
before_install:
    - ./vagrant/travis-before-install.sh
    - phantomjs --version
install:
    - sudo -E ./vagrant/bootstrap.sh
    - pip install selenium
before_script:
script:
    - curl -s http://localhost/redcap/ | grep -i 'Welcome\|Critical Error'
    - ls /var/www/redcap/
    - python tests/test_redcap_hooks.py
after_success:
after_failure:
    - curl -T screenshot-test_redcap_hooks.png http://taeber.rapczak.com/ctsit/test_redcap_hooks.php
after_script:

addons:
    apt:
        packages:
            - apache2
            - mysql-server
            - php5
            - php-pear
            - php5-mysql
            - php5-curl
