language: python
python: '2.7'
branches:
    only:
        - /^feature.*$/
        - /^redcap.*$/
        - develop
        - master
env:
    - CI_REDCAP_ZIP=redcap6.5.3.zip SHARED_FOLDER=./vagrant
before_install: ./vagrant/travis-before-install.sh
install: sudo -E ./vagrant/bootstrap.sh
before_script:
script:
    - curl -s http://localhost/redcap/ | grep -i 'Welcome\|Critical Error'
    - ls /var/www/redcap/
after_success:
after_failure:
after_script:
