language: python
python: '2.7'
sudo: required

branches:
    only:
        - /^feature.*$/
        - /^redcap.*$/
        - develop
        - master
env:
  global:
    - CI_REDCAP_ZIP=releases-lts/redcap6.5.3.zip SHARED_FOLDER=./vagrant
    - CI_REDCAP_ZIP=releases-lts/redcap6.5.9.zip SHARED_FOLDER=./vagrant
    - CI_REDCAP_ZIP=releases-standard/redcap6.8.0.zip SHARED_FOLDER=./vagrant
addons:
  sauce_connect:
    username: ctsit
    access_key: c600f49a-9697-4358-8c3e-2e74c26f9f2f
before_install:
    - ./vagrant/travis-before-install.sh
install:
    - sudo -E ./vagrant/bootstrap.sh
    - phantomjs --version
    - pip install selenium
    - pip freeze | grep selenium
    - apachectl -V
script:
    - curl -s http://localhost/redcap/ | grep -i 'Welcome\|Critical Error'
    - ls /var/www/redcap/
    - python tests/test_redcap_hooks.py

#addons:
#    apt:
#        packages:
#            - apache2
#            - mysql-server
#            - php5
#            - php-pear
#            - php5-mysql
#            - php5-curl
